### ISSUE TITLE
Gene Expression Essentials Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gene-expression-essentials#2]
## Design
- [x] **Sim folder and design doc created** (Date: 04/18/2015) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Legacy sim docs/info gathered**
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
- [x] **Learning goals and standards identified** (Date: 04/23/2015)
- [x] **Design concept complete**  (Date: 04/23/2015)
- [x] **Wireframes complete** (Date: 04/23/2015) 
- [x] **Mockups complete** (Date: 04/30/2015) 
  - [x] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- <s> **Interviews complete** (Date: //) 
  - Results reported to team
  - Notes pasted into design doc
  - Back-up of interviews </s>
- [x] **Lead designer "sign off"** (Date: 12/20/2017) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [ ] Sim primer draft
- [x] **Post-publication items** 
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources), remove legacy version (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 04/10/2015)
  - [x] Add the simulation to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ filesr
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked to pull from rosetta to avoid conflicts.
- [x] **Development started** (Date: 04/18/2015)
- [x] **Sim is "feature complete"** (Date: 04/19/2017) 
- [x] **Code review completed** (Date: 05/08/2017)
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Verify credits
- [x] **Published** (Date: 12/20/2017) 
  - [x] README.md updated using `grunt published-readme` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing complete** (Date: 11/7/2017) 
- [x] **First RC published** (Date: 11/13/2017)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 12/20/2017)

**Comment by ariel-phet** [comment]
## Design
- [ ] **Sim folder and design doc created** (Date: //) 
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Legacy sim docs/info gathered**
  - [ ] Sim suggestions doc reviewed
  - [ ] Unfuddle tickets reviewed
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [ ] Sim primer draft
  - [ ] Verify credits
- [ ] **Post-publication items** 
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources), remove legacy version (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [ ] **Repository created** (Date: //)
  - [ ] simula-rasa used to create project skeleton
  - [ ] README.md created using `grunt unpublished-readme`
  - [ ] Collaborators added (such as QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to chipper/data/ filesr
  - [ ] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can
  be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked
  to pull from rosetta to avoid conflicts.
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //) 
- [ ] **Code review completed** (Date: //) 
- [ ] **Published** (Date: //) 
  - [ ] README.md updated using `grunt published-readme` (in master and release branch)

## QA
- [ ] **Legacy sim tested for bugs**; issues reported in repo
- [ ] **Dev testing complete** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)

**Comment by jbphet** [comment]
Assigning to @ariel-phet for next steps now that a first RC has been published.

**Comment by arouinfar** [comment]
@phet-steele Teacher Tips have been uploaded and backed up on Drive.

**Comment by jbphet** [comment]
I think I've done all of the developer steps.  It looks like there are still a handful of post-publication steps to complete.  @ariel-phet - are these in your court and, if not, who should do them?

**Comment by ariel-phet** [comment]
Sim primer issue created, no postmortem. Closing
